# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag

domain: queenkirathepansexualpixie.github.io
url: https://queenkirathepansexualpixie.github.io
baseurl: /jekyll_test_site/

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
